import api from "../../api";
const materials = {
  namespaced: true,
  state: {
    Input: "",
    InputList: [],
    isActive: {
      H: false,
      He: false,
      Li: false,
      Be: false,
      B: false,
      C: false,
      N: false,
      O: false,
      F: false,
      Ne: false,
      Na: false,
      Mg: false,
      Al: false,
      Si: false,
      P: false,
      S: false,
      Cl: false,
      Ar: false,
      K: false,
      Ca: false,
      Sc: false,
      Ti: false,
      V: false,
      Cr: false,
      Mn: false,
      Fe: false,
      Co: false,
      Ni: false,
      Cu: false,
      Zn: false,
      Ga: false,
      Ge: false,
      As: false,
      Se: false,
      Br: false,
      Kr: false,
      Rb: false,
      Sr: false,
      Y: false,
      Zr: false,
      Nb: false,
      Mo: false,
      Tc: false,
      Ru: false,
      Rh: false,
      Pd: false,
      Ag: false,
      Cd: false,
      Ln: false,
      Sn: false,
      Sb: false,
      Te: false,
      I: false,
      Xe: false,
      Cs: false,
      Ba: false,
      La: false,
      Hf: false,
      Ta: false,
      W: false,
      Re: false,
      Os: false,
      Ir: false,
      Pt: false,
      Au: false,
      Hg: false,
      Tl: false,
      Pb: false,
      Bi: false,
      Po: false,
      At: false,
      Rn: false,
      Fr: false,
      Ra: false,
      Ac: false,
      Rf: false,
      Db: false,
      Sg: false,
      Bh: false,
      Hs: false,
      Mt: false,
      Ds: false,
      Rg: false,
      Uub: false,
      Uut: false,
      Uuq: false,
      Uup: false,
      Uuh: false,
      Uus: false,
      Uuo: false,
      Ce: false,
      Pr: false,
      Nd: false,
      Pm: false,
      Sm: false,
      Eu: false,
      Gd: false,
      Tb: false,
      Dy: false,
      Ho: false,
      Er: false,
      Tm: false,
      Yb: false,
      Lu: false,
      Th: false,
      Pa: false,
      U: false,
      Np: false,
      Pu: false,
      Am: false,
      Cm: false,
      Bk: false,
      Cf: false,
      Es: false,
      Fm: false,
      Md: false,
      No: false,
      Lr: false,
    },
    InputParams: "",
    List: [],
    total: null,
    page: "",
    sort: "",
  },
  mutations: {
    save(state, Element) {
      state.Input = Element;
    },
    saveInput(state, ElementList) {
      state.InputList = ElementList;
    },
    lightElement(state, ele) {
      state.isActive[ele] = true;
    },
    clearLight(state) {
      state.isActive = {
        H: false,
        He: false,
        Li: false,
        Be: false,
        B: false,
        C: false,
        N: false,
        O: false,
        F: false,
        Ne: false,
        Na: false,
        Mg: false,
        Al: false,
        Si: false,
        P: false,
        S: false,
        Cl: false,
        Ar: false,
        K: false,
        Ca: false,
        Sc: false,
        Ti: false,
        V: false,
        Cr: false,
        Mn: false,
        Fe: false,
        Co: false,
        Ni: false,
        Cu: false,
        Zn: false,
        Ga: false,
        Ge: false,
        As: false,
        Se: false,
        Br: false,
        Kr: false,
        Rb: false,
        Sr: false,
        Y: false,
        Zr: false,
        Nb: false,
        Mo: false,
        Tc: false,
        Ru: false,
        Rh: false,
        Pd: false,
        Ag: false,
        Cd: false,
        Ln: false,
        Sn: false,
        Sb: false,
        Te: false,
        I: false,
        Xe: false,
        Cs: false,
        Ba: false,
        La: false,
        Hf: false,
        Ta: false,
        W: false,
        Re: false,
        Os: false,
        Ir: false,
        Pt: false,
        Au: false,
        Hg: false,
        Tl: false,
        Pb: false,
        Bi: false,
        Po: false,
        At: false,
        Rn: false,
        Fr: false,
        Ra: false,
        Ac: false,
        Rf: false,
        Db: false,
        Sg: false,
        Bh: false,
        Hs: false,
        Mt: false,
        Ds: false,
        Rg: false,
        Uub: false,
        Uut: false,
        Uuq: false,
        Uup: false,
        Uuh: false,
        Uus: false,
        Uuo: false,
        Ce: false,
        Pr: false,
        Nd: false,
        Pm: false,
        Sm: false,
        Eu: false,
        Gd: false,
        Tb: false,
        Dy: false,
        Ho: false,
        Er: false,
        Tm: false,
        Yb: false,
        Lu: false,
        Th: false,
        Pa: false,
        U: false,
        Np: false,
        Pu: false,
        Am: false,
        Cm: false,
        Bk: false,
        Cf: false,
        Es: false,
        Fm: false,
        Md: false,
        No: false,
        Lr: false,
      };
    },
    addElement(state, ele) {
      state.InputList.push(ele);
      state.Input += ele;
    },
    delElement(state, ele) {
      state.InputList = state.InputList.filter((x) => x !== ele);
      state.Input = state.Input.replaceAll(ele, "");
    },
    addInput(state, ele) {
      state.Input += ele;
    },
    delInput(state) {
      state.Input = state.Input.substring(0, state.Input.length - 1);
    },
    changeInputParams(state, params) {
      state.InputParams = params;
    },
    changePage(state, page) {
      state.page = page;
    },
    changeSort(state, sortParams) {
      const sort = { sort: JSON.stringify(sortParams) };
      state.sort = sort;
    },
    async commitSearch(state, rank) {
      let params = { Input: state.Input };
      switch (rank) {
        case "rough":
          break;
        case "advanced":
          params = Object.assign(params, state.InputParams);
          break;
        case "careful":
          params = Object.assign(
            params,
            state.InputParams,
            state.page,
            state.sort
          );
          break;
      }
      const { List: List, page: page } = await api.findMaterialsAbstracts(
        params
      );
      state.List = List;
      state.total = page.total;
    },
  },
};

export default materials;
